version: '3.5'

services:

  web:
    container_name: web
    build:
      context: ./ng-app
      dockerfile: Dockerfile
    volumes:
      - './ng-app/:/converzapp'
      - '/converzapp/node_modules'
    ports:
      - '4200:4200'
    # This makes the container run on the same network stack as your
    # workstation. Meaning that you can interact on "localhost".
    network_mode: host
    command: ["npm", "start"]
    environment:
      - NODE_ENV=development
    depends_on:
      - gateway
  
  gateway:
    container_name: gateway
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    command: ["./gateway.bin"]

  web-prod:
    container_name: web-prod
    build:
      context: ./
      dockerfile: /ng-app/Dockerfile-prod
    ports:
      - '80:80'
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - gateway
    network_mode: host