#########################
### build environment ###
#########################

# base image
FROM node:10-alpine as builder

# set working directory
WORKDIR /usr/src/app
COPY ./ng-app /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
RUN npm install --silent

# generate build
RUN npm run build

##################
### production ###
##################

# base image
FROM nginx:1.13.9-alpine

# copy artifact build from the 'build environment'
COPY --from=builder /usr/src/app/dist/ng-app-v2 /usr/share/nginx/html
COPY ngnix-config.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
